# Site
repository: jivanandham/jivanandham.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Jeeva Krishnasamy
title: Techie
email: jivanandham@gmail.com
website: jivanandham.github.io
resume: resume/Jeeva Krishnasamy Resume.pdf


# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: jiiivanandham
github_username:  jivanandham
gmail_username: jivanandham@gmail.com
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: jivanandham
linkedin_username: jivanandham
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jivanandham
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
  # icon: fas fa-globe
  # url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/PXL_20230930_195442661.MP.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Jeeva, Electrical Engineer with 8 years of experience in designing, implementing, and maintaining electrical systems. Seeking a transition into the Information Technology domain to leverage technical expertise, problem-solving abilities, and project management skills for IT-related roles.

 # I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

        

content:
  - title: Skills # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Technical Skills
        # caption: List of technical skills
        sub_title: 
        description: | 
          Python, Java, R, SQL, React, HTML, CSS, JavaScript, Node.js, MongoDB, AWS, TensorFlow, scikit-learn, TCP/IP, DNS, VPN, Linux, Windows
          
      - layout: left
        title: Soft Skills
        # caption: List of soft skills
        sub_title: 
        description: | 
          Communication, Team Collaboration, Problem Solving, Critical Thinking, Time Management, Adaptability, Leadership, Creativity, Attention to Detail, Conflict Resolution
        
  - title: Certifications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Certifications
        # caption: List of technical skills
        sub_title: 
        description: | 
          Udacity - Data Analyst Nanodegree: Python; SQL; Data Analysis; Data Visualization.
          
          IBM - Data Science Specialization: Python; SQL; Data Exploration.
          
          Google IT Support Professional Certificate: IT Security; Network Fundamentals; Scripting.
          
          Scaler Full Stack Specialization: Java; SQL; LLD; HLD.

  
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Pittsburgh
        caption: 2023 - Present
        sub_title: Master of Science in Information Science GPA - 3.875
        
        # quote: >
          # Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          Currently pusuing Master's at UPitt I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          Graduate Coursework: Algorithm Design, Applications of Networks, Database Management, Cyber Forensic, Machine Learning, Cloud Computing, Artifical Intelligence, Information Security and Privacy.     
        
      - layout: left
        title: Tamil Nadu Agricultural University
        caption: 2017 - 2019 
        sub_title: Master of Business Administration (Part-Time) GPA - 3.00
        # quote: >
          # Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          My MBA journey is not just a qualification—it's a testament to my commitment to excellence and continuous learning. The strategic mindset, analytical prowess, and specialized knowledge I gained during my MBA program contribute significantly to my ability to deliver impactful solutions.
          
          Graduate Coursework: Statistics, Research Methodology, Strategy Formation, Financial Management.
      - layout: left
        title: Anna University
        caption: 2009 - 2013
        sub_title: Bachelors of Engineering Electrical and Electronics GPA - 3.50
        # quote: >
          # Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          I hold a Bachelor's degree in Electrical and Electronics Engineering, where I excelled in both theoretical knowledge and practical applications. My hands-on experience, specialization in both Electrical and Electronics, and recognition for underscore my commitment to innovation in the ever-evolving field of electrical engineering.
      
          Undergraduate Coursework: Data Structures, Object oriented Programming, Digital Signal Processing, Computer Networks.

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Archaeology Database
        icon: fab fa-github
        link: github.com/jivanandham/Database-Management-INFSCI-2710
        # link_text: Project Website
        description: | # this will include new lines to allow paragraphs
          •	Led the construction of a database and website for the university's Archaeological Department. Successfully implemented roles for dynamic data entry, versioning, and user access, integrating features such as variable fields, data dictionary, and time-stamped snapshots. (React, Postgres, AWS, Node.js)
      - layout: left
        title: Deepfake Detection using ResNet
        icon: fab fa-github
        link: https://github.com/jivanandham/Cyber-Forensics-Deepfake-Detection
        # link_text: Project Website
        description: | # this will include new lines to allow paragraphs
          •	Implemented and assessed a deepfake detection system using InceptionResNetV2 with fine-tuning and image augmentation.. (Python, TensorFlow)
      - layout: left
        title: Network Simulator
        icon: fab fa-github
        link: github.com/jivanandham/Applications-of-Networks-main
        # link_text: Project Website
        description: | # this will include new lines to allow paragraphs
          •	Developed expertise in Network Simulation and Internet Measurement and Analysis. Proficiently utilized tools and methodologies to simulate network environments and conducted in-depth analysis, showcasing a strong understanding of network dynamics. (Python, Matplotlib)
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Electrical Engineer 
        # link_text: boringcompany.com
        sub_title: Shraddha Engineering and Facilty Services
        link: http://sefs.co.in
        caption: June 2020 - December 2022
        # quote: >
          # Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Functioned as crew leader, overseeing the work of 30 lower-level licensed electricians and trade helpers. Followed electrical code manuals to install and repair electrical systems.
            
            Took ownership of electrical crew schedule, developing short- and long-term look-ahead schedules toalign with execution plans.
            
            Meticulously tested installations to check continuity of circuits and compatibility and safety ofcomponents using test equipment such as an ohmmeter, amp meter, and voltmeter.
            
            Provided technical supervision and support to Instrumentation and Electrical (I&E) supervisors,Instrument and electrical planners, and contract personnel. Coordinated efficient maintenance schedules to keep systems running at peak levels.

      - layout: left
        title: Senior Electrical Technician 
        # link_text: boringcompany.com
        sub_title: Blue Star
        link: bluestarindia.com
        caption: April 2018 - June 2020
        # quote: >
          # Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Improved efficiency in electrical distribution, cutting downtime and boosting operational reliability by 20%.
            
            Performed monthly, semi-annual, and annual Preventive Maintenance Checks and Services (PMCS).
            
            Kept permits, isolation tags, and logs currently at all times. Drafted and completed daily, weekly and monthly checklist for building equipment maintenance.
            
            Maintained electrical and mechanical components of gas and diesel engine-driven generators. Provided electrical services and control wiring for diverse locations.

            
      - layout: left
        title: Electrical Technician 
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Chennai Engineering Services
        caption: June 2015 - April 2018
        # quote: >
          # Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Interpreted and executed intricate electrical schematics, blueprints, and diagrams, contributing to the completion of 10+ projects with accurate wiring and optimal functionality.

            Installed electrical wiring during remodeling projects. Frequently worked overtime, weekends, and holidays. Interpreted electrical and mechanical schematics, blueprints, and diagrams.
            
            Tested energized and de-energized circuits, following test procedures and assisted in specialized testprocedures. Tested and repaired electric motors, variable frequency drives, alarms, and control systems.

      - layout: left
        title: Apprentice Electrical Engineer
        # link_text: boringcompany.com
        sub_title: TANGEDCO
        link: www.tangedco.org
        caption: March 2014 - March 2015
        # quote: >
          # Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Managed operations at a hydro power plant, ensuring compliance with safety and environmental regulations.
            
            Implemented data monitoring for predicative maintenance of the generators and transmission lines.

            Operation and Maintenance of Hydro Power Plant. 3 * 60 MW Generator, 9 * 11/230 KV Transformers, 230 KV Switchyard, 230 KV Transmission Lines and its Auxiliaries.


  # - title: A Little More About Me
  #   layout: text
  #   content: | # this will include new lines to allow paragraphs
  #     Alongside my interests in networks and software engineering some of my other interests and hobbies are:
  #     - Rock climbing
  #     - Gaming
  #     - Knitting
  #     - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

  #     Look at this cool image  
  #     ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
