# Site
repository: jivanandham/jivanandham.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Jeeva Krishnasamy
title: 
email: jivanandham@gmail.com
website: jivanandham.github.io

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: jiiivanandham
github_username:  jivanandham
gmail_username: jivanandham@gmail.com
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: jivanandham
linkedin_username: jivanandham
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: jivanandham
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
  # icon: fas fa-globe
  # url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/PXL_20230930_195442661.MP.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Jeeva, Electrical Engineer with 8 years of experience in designing, implementing, and maintaining electrical systems. Seeking a transition into the Information Technology domain to leverage technical expertise, problem-solving abilities, and project management skills for IT-related roles.

 # I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

        

content:
- title: Skills # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Programming Languages
        description: | # this will include new lines to allow paragraphs
            Python, Java, SQL
       - layout: left
        title: Programming Languages
        description: | # this will include new lines to allow paragraphs
            Python, Java, SQL
    
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Pittsburgh
        caption: 2023 - Present
        sub_title: Master of Science in Information Science GPA - 3.75
        
        # quote: >
          # Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          Currently pusuing Master's at UPitt I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          Graduate Coursework: Algorithm Design, Applications of Networks, Database Management, Cyber Forensic, Machine Learning, Cloud Computing, Artifical Intelligence.     
        
      - layout: left
        title: Tamil Nadu Agricultural University
        caption: 2017 - 2019 
        sub_title: Master of Business Administration (Part-Time) GPA - 3.00
        # quote: >
          # Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          My MBA journey is not just a qualification—it's a testament to my commitment to excellence and continuous learning. The strategic mindset, analytical prowess, and specialized knowledge I gained during my MBA program contribute significantly to my ability to deliver impactful solutions.
          
          Graduate Coursework: Statistics, Research Methodology, Strategy Formation, Financial Management.
      - layout: left
        title: Anna University
        caption: 2009 - 2013
        sub_title: Bachelors of Engineering Electrical and Electronics GPA - 3.50
        # quote: >
          # Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          I hold a Bachelor's degree in Electrical and Electronics Engineering, where I excelled in both theoretical knowledge and practical applications. My hands-on experience, specialization in both Electrical and Electronics, and recognition for underscore my commitment to innovation in the ever-evolving field of electrical engineering.
      
          Undergraduate Coursework: Data Structures, Object oriented Programming, Digital Signal Processing, Computer Networks.

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Archaeology Database
        icon: fab fa-github
        link: github.com/Database-Management-INFSCI-2710
        # link_text: Project Website
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.
      - layout: left
        title: Super awesome project
        icon: fab fa-github
        link: github.com/sproogen
        # link_text: Project Website
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.


  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Shraddha Engineering and Facilty Services
        link: http://sefs.co.in
        # link_text: boringcompany.com
        sub_title: Electrical Supervisor
        caption: June 2020 - December 2022
        # quote: >
          # Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            •	Functioned as crew leader, overseeing the work of 30 lower-level licensed electricians and trade helpers.
            
            •	Provided technical supervision and support to Instrumentation and Electrical personnel.

      - layout: left
        title: Blue Star
        link: bluestarindia.com
        # link_text: boringcompany.com
        sub_title: Electrical Technician
        caption: April 2018 - June 2020
        # quote: >
          # Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            • Improved efficiency in electrical distribution, cutting downtime and boosting operational reliability by 20%.
            • Performed monthly, semi-annual, and annual Preventive Maintenance Checks and Services (PMCS).
            
      - layout: left
        title: Chennai Engineering Services
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Electrical Technician
        caption: June 2015 - April 2018
        # quote: >
          # Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            • Interpreted and executed intricate electrical schematics, blueprints, and diagrams, contributing to the completion of 10+ projects with accurate wiring and optimal functionality.
      - layout: left
        title: TANGEDCO
        link: www.tangedco.org
        # link_text: boringcompany.com
        sub_title: Graduate Trainee
        caption: March 2014 - March 2015
        # quote: >
          # Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            • Managed operations at a hydro power plant, ensuring compliance with safety and environmental regulations.
            • Implemented data monitoring for predicative maintenance of the generators and transmission lines.
  - title: Certifications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Boring Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        # quote: >
          # Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.
      
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
