# Site
repository: jivanandham/jivanandham.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Jeeva Krishnasamy
title: Electrical Engineer
email: jek283@pitt.edu
website: github.com/jivanandham
linkedin_username: jivanandham
twitter_username: # Add your Twitter username
github_username: jivanandham
instagram_username: # Add your Instagram username
youtube_username: # Add your YouTube username

# Dark Mode (true/false/never)
darkmode: true

# About Section
about_profile_image: # Add the path to your profile image
about_content: |
  Electrical Engineer with 8 years of experience in designing, implementing, and maintaining electrical systems. Seeking a transition into the Information Technology domain to leverage technical expertise, problem-solving abilities, and project management skills for IT-related roles.

# Education Section
content:
  - title: Education
    layout: list
    content:
      - layout: left
        title: University of Pittsburgh
        caption: Expected December 2024
        sub_title: Master of Science, Information Science, GPA - 3.75
        description: |
          Graduate Coursework: Algorithm Design, Applications of Networks, Database Management, Cyber Forensic

      - layout: left
        title: Tamil Nadu Agricultural University
        caption: September 2019
        sub_title: Master of Business Administration (Part-Time), GPA - 3.0
        description: |
          Graduate Coursework: Statistics, Research Methodology, Strategy Formation

      - layout: left
        title: Anna University
        caption: April 2013
        sub_title: Bachelor of Electrical and Electronics Engineering, GPA - 3.5
        description: |
          Undergraduate Coursework: Data Structures and Algorithms, Computer Networks

# Projects Section
  - title: Projects
    layout: list
    content:
      - layout: left
        title: Archaeological Database
        caption: August 2023 – December 2023
        description: |
          Led the construction of a database and website for the university's Archaeological Department. Successfully implemented roles for dynamic data entry, versioning, and user access, integrating features such as variable fields, data dictionary, and time-stamped snapshots. (React, Postgres, AWS, Node.js)

      - layout: left
        title: Network Simulator
        caption: August 2023 – December 2023
        description: |
          Developed expertise in Network Simulation and contributed significantly to an Internet Measurement and Analysis Project. Proficiently utilized tools and methodologies to simulate network environments and conducted in-depth analysis, showcasing a strong understanding of network dynamics. (Python)

# Experience Section
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Electrical Supervisor
        caption: June 2020 - December 2022
        sub_title: Shraddha Engineering and Facility Services, Coimbatore, India
        description: |
          Functioned as crew leader, overseeing the work of 30 lower-level licensed electricians and trade helpers. Provided technical supervision and support to Instrumentation and Electrical personnel.

      - layout: left
        title: Electrical Technician
        caption: April 2018 - June 2020
        sub_title: Blue Star Limited, Coimbatore, India
        description: |
          Improved efficiency in electrical distribution, cutting downtime and boosting operational reliability by 20%. Performed monthly, semi-annual, and annual Preventive Maintenance Checks and Services (PMCS).

      - layout: left
        title: Electrical Technician
        caption: June 2015 - April 2018
        sub_title: Chennai Engineering Services, Coimbatore, India
        description: |
          Interpreted and executed intricate electrical schematics, blueprints, and diagrams, contributing to the completion of 10+ projects with accurate wiring and optimal functionality.

      - layout: left
        title: Graduate Trainee
        caption: March 2014 - February 2015
        sub_title: TANGEDCO, Ooty, India
        description: |
          Managed operations at a hydro power plant, ensuring compliance with safety and environmental regulations. Implemented data monitoring for predicative maintenance of the generators and transmission lines.

# Certifications Section
  - title: Certifications
    layout: list
    content:
      - layout: left
        title: Udacity - Data Analyst Nanodegree
        caption: Python; SQL; Data Analysis; Data Visualization.

      - layout: left
        title: IBM - Data Science Specialization
        caption: Python; SQL; Data Exploration.

      - layout: left
        title: Google IT Support Professional Certificate
        caption: IT Security; Network Fundamentals; Scripting.

      - layout: left
        title: Scaler Full Stack Specialization
        caption: Java; SQL; LLD; HLD.

# Honors Section
  - title: Honors
    layout: text
    content: |
      Class Topper at Bachelor of Electrical and Electronics Engineering, GPA - 3.5.

# Footer
footer_show_references: true
